[theme]
primaryColor = "#0F62FE"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F4F4F5"
textColor = "#1C1917"
font = "sans serif"

[server]
maxUploadSize = 10
enableXsrfProtection = true

[browser]
gatherUsageStats = false